// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
    devtools: { enabled: true },
    app: {
        head: {
            meta: [
                // generated by https://realfavicongenerator.net
                {
                    name: 'msapplication-TileColor',
                    content: '#ffffff',
                },
                {
                    name: 'theme-color',
                    content: '#ffffff',
                },
            ],
            link: [
                // material icons
                {
                    rel: 'stylesheet',
                    href: 'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght@300',
                },
                {
                    rel: 'preconnect',
                    href: 'https://fonts.googleapis.com',
                },
                {
                    rel: 'preconnect',
                    href: 'https://fonts.gstatic.com',
                    crossorigin: 'anonymous',
                },
                {
                    href: 'https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700&display=swap',
                    rel: 'stylesheet',
                },
                {
                    rel: 'icon',
                    type: 'image/x-icon',
                    href: '/favicon.ico',
                },
                // generated by https://realfavicongenerator.net/
                {
                    rel: 'apple-touch-icon',
                    sizes: '180x180',
                    href: '/apple-touch-icon.png',
                },
                {
                    rel: 'icon',
                    type: 'image/png',
                    sizes: '32x32',
                    href: '/favicon-32x32.png',
                },
                {
                    rel: 'icon',
                    type: 'image/png',
                    sizes: '16x16',
                    href: '/favicon-16x16.png',
                },
                {
                    rel: 'manifest',
                    href: '/site.webmanifest',
                },
                {
                    rel: 'mask-icon',
                    href: '/safari-pinned-tab.svg',
                    color: '#9d8b73',
                },
            ],
        },
    },
    css: [
        'primeicons/primeicons.css', // prime icons
        '~/assets/theme/themes/mytheme/theme.scss', // prime components
        '~/assets/theme/primeflex/primeflex.scss', // prime flex utilities
        '~/assets/theme/eg-custom.scss', // everygram custom styles
    ],
    routeRules: {
        '/': { ssr: true },
        '/trip-share/**': { ssr: true },
        '/public-trips': { ssr: false },

        // pages that require authentication
        '/gears': { ssr: false },
        '/gears-editor': { ssr: false },
        '/archived-gears': { ssr: false },
        '/trips': { ssr: false },
        '/trip/**': { ssr: false },
    },
    modules: ['@pinia/nuxt', 'nuxt-lodash', '@nuxtjs/i18n', 'nuxt-primevue'],
    lodash: {
        // https://nuxt.com/modules/lodash#config
        prefix: '_',
        upperAfterPrefix: false,
    },
    i18n: {
        langDir: 'locales',
        locales: [
            {
                code: 'en',
                name: 'English',
                iso: 'en-US',
                file: 'en.json',
            },
            {
                code: 'zh-tw',
                name: '繁體中文',
                iso: 'zh-TW',
                file: 'zh-tw.json',
            },
        ],
        defaultLocale: 'en',
        strategy: 'no_prefix',
        detectBrowserLanguage: {
            useCookie: true,
            cookieKey: 'i18n_redirected',
        },
        experimental: {
            localeDetector: './localeDetector.ts',
        },
    },
    primevue: {
        components: {
            prefix: 'Prime',
        },
    },
    experimental: {
        viewTransition: false,
    },
});
